name: pure_di
description: "A lightweight, pure Dart dependency injection library with lazy singletons and scoped instances. Zero external dependencies."
version: 0.0.2
homepage: "https://github.com/suhail7cb/pure_di"


environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


topics:
  - dependency-injection
  - service-locator
  - singleton
  - scoped
  - di-flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
